export class EVENTS {
  static APPLY = "APPLY";

  static RUN_INSERT_MESSAGES = "RUN_INSERT_MESSAGES";
  static INSERT_MESSAGE = "INSERT_MESSAGE";

  static RUN_APPLY = "RUN_APPLY";
  static APPLIED = "APPLIED";

  static START_SYNC = "START_SYNC";
  static STOP_SYNC = "STOP_SYNC";
  static SELECT_GROUP = "SELECT_GROUP";
  static ADD_GROUP = "ADD_GROUP";
  static ADD_SCHEMA = "ADD_SCHEMA";
  static INIT = "INIT";
  static SEND_MESSAGE = "SEND_MESSAGE";

  static GET_MERKLE = "GET_MERKLE";
  static MERKLE = "MERKLE";

  static ADD_ENCRYPTION_URL = "ADD_ENCRYPTION_URL";

  static GET_MOST_RECENT_LOCAL_MESSAGES = "GET_MOST_RECENT_LOCAL_MESSAGES";
  static MOST_RECENT_LOCAL_MESSAGES = "MOST_RECENT_LOCAL_MESSAGES";
}

